version: '3.4'

services:
  civicbucksminer:
    image: tauseefl/civicbucksminer
    build:
      context: ./miner_server
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
  civicbucksmain:
    image: tauseefl/civicbucksmain
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    depends_on: 
      - civicbucksminer
